Default: &defaults
  database: BlogTest.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: BlogTest_test.sqlite3
  <<: *defaults

Staging:
  database: BlogTest_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: BlogTest_production.sqlite3
  poolsize: 100
  <<: *defaults
